#!/bin/bash
#sh MAKEFILE
git pull
apt-get update

npm install -g npm@latest

npm install
# audit Fix Auto and list modules
npm audit fix
npm list -g --depth 0
npm list
pm2 update

#  Verifies the contents of the cache folder, garbage collecting any unneeded data, and verifying the integrity of the cache index and all cached data
npm cache verify

# remove logs
rm /home/ubuntu/.npm/_logs/*
echo "----done------"

pm2 stop webrtcsignaller
pm2 delete webrtcsignaller
if [[ "$HOSTNAME" == "ip-172-31-9-100" ]]
then
    printf '%s\n' "on prod"
    export NODE_ENV="prod"
    pm2 start ecosystem.config.js --env prod
elif [[ "$HOSTNAME" == "ip-172-31-21-121" ]]
then
    printf '%s\n' "on dev "
    export NODE_ENV="dev"
    pm2 start ecosystem.config.js --env dev
else
    printf '%s\n' "on other test host"
    export NODE_ENV="test"
    pm2 start ecosystem.config.js --env test
fi


echo "----server started------"
#netstat -anp
pm2 monit
